Update patch set 3
Patch Set 3:

--> rubygem-rspec-3.5.0-1.el7.noarch
DEBUG util.py:417:  Error: Package: rubygem-rspec-expectations-2.14.5-2.el7.1.noarch (build)
DEBUG util.py:417:             Requires: rubygem(diff-lcs)
DEBUG util.py:417:  Error: Package: rubygem-rspec-3.5.0-1.el7.noarch (build)
DEBUG util.py:417:             Requires: rubygem(rspec-core) >= 3.5.0
DEBUG util.py:417:             Installing: rubygem-rspec-core-2.14.8-1.el7.0.noarch (build)
DEBUG util.py:417:                 rubygem(rspec-core) = 2.14.8-1.el7.0
DEBUG util.py:417:  Error: Package: rubygem-rspec-3.5.0-1.el7.noarch (build)
DEBUG util.py:417:             Requires: rubygem(rspec-mocks) >= 3.5.0
DEBUG util.py:417:             Installing: rubygem-rspec-mocks-2.14.6-2.el7.1.noarch (build)
DEBUG util.py:417:                 rubygem(rspec-mocks) = 2.14.6-2.el7.1
DEBUG util.py:417:  Error: Package: rubygem-rspec-3.5.0-1.el7.noarch (build)
DEBUG util.py:417:             Requires: rubygem(rspec-expectations) >= 3.5.0
DEBUG util.py:417:             Installing: rubygem-rspec-expectations-2.14.5-2.el7.1.noarch (build)
DEBUG util.py:417:                 rubygem(rspec-expectations) = 2.14.5-2.el7.1

Patch-set: 3