Update patch set 5
Patch Set 5:

Different failure now:
```
 --> rubygem-rspec-3.5.0-1.el7.noarch
Error: Package: rubygem-rspec-expectations-2.14.5-2.el7.1.noarch (build)
           Requires: rubygem(diff-lcs)
Error: Package: rubygem-rspec-3.5.0-1.el7.noarch (build)
           Requires: rubygem(rspec-mocks) >= 3.5.0
           Installing: rubygem-rspec-mocks-2.14.6-2.el7.1.noarch (build)
               rubygem(rspec-mocks) = 2.14.6-2.el7.1
```

Patch-set: 5
Reviewer: Gerrit User 326 <326@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0